# Generated by Django 5.0.6 on 2024-06-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
